//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScaleniaMW.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathFDB {
            get {
                return ((string)(this["PathFDB"]));
            }
            set {
                this["PathFDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
            set {
                this["Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Haslo {
            get {
                return ((string)(this["Haslo"]));
            }
            set {
                this["Haslo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathEDZ {
            get {
                return ((string)(this["PathEDZ"]));
            }
            set {
                this["PathEDZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathGeneruj {
            get {
                return ((string)(this["PathGeneruj"]));
            }
            set {
                this["PathGeneruj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxignorujKropkeIPrzecinek {
            get {
                return ((bool)(this["checkBoxignorujKropkeIPrzecinek"]));
            }
            set {
                this["checkBoxignorujKropkeIPrzecinek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxBrakKW {
            get {
                return ((bool)(this["checkBoxBrakKW"]));
            }
            set {
                this["checkBoxBrakKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxDopiszBlad {
            get {
                return ((bool)(this["checkBoxDopiszBlad"]));
            }
            set {
                this["checkBoxDopiszBlad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CzyBlokowacProgram {
            get {
                return ((bool)(this["CzyBlokowacProgram"]));
            }
            set {
                this["CzyBlokowacProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int OdsumieciePionoweTekstu {
            get {
                return ((int)(this["OdsumieciePionoweTekstu"]));
            }
            set {
                this["OdsumieciePionoweTekstu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int JustyfikacjNKR {
            get {
                return ((int)(this["JustyfikacjNKR"]));
            }
            set {
                this["JustyfikacjNKR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int JustyfikacjaWartosci {
            get {
                return ((int)(this["JustyfikacjaWartosci"]));
            }
            set {
                this["JustyfikacjaWartosci"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckBoxPodkreslenieNKR {
            get {
                return ((bool)(this["CheckBoxPodkreslenieNKR"]));
            }
            set {
                this["CheckBoxPodkreslenieNKR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckBoxPodkreslenieWARTOSCI {
            get {
                return ((bool)(this["CheckBoxPodkreslenieWARTOSCI"]));
            }
            set {
                this["CheckBoxPodkreslenieWARTOSCI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckBoxPodzialSekcji {
            get {
                return ((bool)(this["CheckBoxPodzialSekcji"]));
            }
            set {
                this["CheckBoxPodzialSekcji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3051")]
        public int FBPort {
            get {
                return ((int)(this["FBPort"]));
            }
            set {
                this["FBPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EwopisPort3050 {
            get {
                return ((bool)(this["EwopisPort3050"]));
            }
            set {
                this["EwopisPort3050"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EwopisLogin {
            get {
                return ((string)(this["EwopisLogin"]));
            }
            set {
                this["EwopisLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EwopisHaslo {
            get {
                return ((string)(this["EwopisHaslo"]));
            }
            set {
                this["EwopisHaslo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EwopisSciezkaFDB {
            get {
                return ((string)(this["EwopisSciezkaFDB"]));
            }
            set {
                this["EwopisSciezkaFDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool czyWziacNrJednRejZNkrPo {
            get {
                return ((bool)(this["czyWziacNrJednRejZNkrPo"]));
            }
            set {
                this["czyWziacNrJednRejZNkrPo"] = value;
            }
        }
    }
}
